[package]
name = "cortex-m-edf-rtic"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = [
    "critical-section-single-core",
    "inline-asm",
] }
cortex-m-rt = "0.7.5"
defmt = "1.0.1"
defmt-rtt = "1.1.0"
fugit = { version = "0.3.7", features = ["defmt"] }
heapless = { version = "0.9.1", features = ["defmt", "portable-atomic"] }
panic-probe = { version = "1.0.0", features = ["defmt", "print-defmt"] }
#edf-sw = { path = "../../../edf-sw" }
rtic-edf-pass = { path = "../../compilation_passes/rtic-edf-pass", default-features = false }
atsamd-hal = { version = "0.22.2", default-features = false }
rtic-macro = { path = "rtic-macro" }


[features]
# ask the HAL to enable atsamd51j support
default = ["atsamd-hal/samd51j-rt", "atsamd-hal/samd51j", "atsamd-hal/defmt"]

[build-dependencies]
cc = "1.2.44"

[profile.dev]
opt-level = 0
debug = 2

[profile.release]
opt-level = "s"
debug = 2
lto = "fat"
