[package]
name = "cortex-m-edf-rtic"
version = "0.1.0"
edition = "2024"
authors = ["Justin Beaurivage <code@beaurivage.io>"]

[dependencies]
cortex-m = { version = "0.7.7", features = [
    "critical-section-single-core",
    "inline-asm",
] }
cortex-m-rt = "0.7.5"
rtic-edf-pass = { path = "../../compilation_passes/rtic-edf-pass", default-features = false }
rtic-macro = { path = "rtic-macro" }
benchmark-generator = { path = "benchmark-generator" }

[features]
check-missed-deadlines = ["rtic-edf-pass/check-missed-deadlines"]

[dev-dependencies]
defmt = "1.0.1"
defmt-rtt = "1.1.0"
fugit = { version = "0.3.7", features = ["defmt"] }
panic-probe = { version = "1.0.0", features = ["defmt", "print-defmt"] }

[dev-dependencies.atsamd-hal]
version = "0.23.0"
default-features = false
features = ["samd51j-rt", "samd51j", "defmt"]

[profile.dev]
opt-level = 0
debug = 2

[profile.release]
opt-level = 3
debug = 2
debug-assertions = false
lto = "fat"

[profile.debug-optimized]
inherits = "release"
debug-assertions = true

[[example]]
name = "benchmark"
required-features = ["check-missed-deadlines"]

[[example]]
name = "overhead_bench"
required-features = ["rtic-edf-pass/defmt"]

[[example]]
name = "bench_oh"
# required-features = ["rtic-edf-pass/defmt", "check-missed-deadlines"]
required-features = ["rtic-edf-pass/defmt"]
